"""Translation builders for Conditionals and Iteration fundamentals (batch 2)."""

from __future__ import annotations

# Shared code blocks imported by the main batch script at assembly time.


def _join(*parts: str) -> str:
    return "\n".join(p for p in parts if p is not None)


def cond_index(lang: str) -> tuple[str, str]:
    titles = {
        "de": "Bedingungen", "es": "Condicionales", "fr": "Conditions", "it": "Condizionali",
        "ja": "条件分岐", "ko": "조건문", "nl": "Conditionals", "pl": "Instrukcje warunkowe",
        "pt-br": "Condicionais", "ru": "Условные конструкции", "sv": "Villkor",
        "th": "เงื่อนไข", "zh-cn": "条件语句", "zh-tw": "條件陳述",
    }
    bodies = {
        "de": _join(
            "Bedingungen sind ein grundlegender Bestandteil der Programmierung: Sie ermöglichen Skripten, Entscheidungen zu treffen und ihren Ablauf anhand bestimmter Kriterien zu steuern. In Scheme, basierend auf der Programmiersprache Scheme, helfen Ihnen Bedingungen dabei, dynamische und intelligente Skripte zu schreiben, die sich an veränderte Eingaben, Umgebungen oder Benutzeraktionen anpassen.",
            "", "### Die Rolle von Bedingungen in Scheme", "",
            "Bedingungen erfüllen in Ihren Skripten mehrere zentrale Aufgaben:",
            "- **Steuerung der Logik:** Sie führen je nachdem unterschiedliche Codeteile aus, ob bestimmte Bedingungen wahr oder falsch sind.",
            "- **Mehr Flexibilität:** Durch dynamische Reaktion auf Eingaben oder Zustände bewältigen Ihre Skripte eine Vielzahl von Szenarien.",
            "- **Komplexität reduzieren:** Sie zerlegen Entscheidungen in überschaubare Strukturen und machen Code leichter lesbar, debugbar und wartbar.",
            "", "### Verfügbare bedingte Konstrukte", "",
            "Scheme bietet mehrere bedingte Konstrukte, die jeweils für unterschiedliche logische Anforderungen geeignet sind:",
            "- **`if`:** Für einfache binäre Entscheidungen — ein Codeblock, wenn eine Bedingung wahr ist, ein anderer, wenn sie falsch ist.",
            "- **`cond`:** Ein leistungsstarkes Mehrfachverzweigungskonstrukt für mehrere Bedingungen in klarer, strukturierter Form.",
            "- **`and` / `or`:** Logische Operatoren, die Kombinationen von Bedingungen auswerten und komplexere Entscheidungen ermöglichen.",
            "- **`else`:** Ein Fallback, der das Verhalten definiert, wenn keine der angegebenen Bedingungen zutrifft.",
            "", "### So funktionieren Bedingungen", "",
            "Bedingungen umfassen typischerweise:",
            "1. **Bedingung auswerten:** Ein Testausdruck bestimmt, ob eine Bedingung wahr oder falsch ist.",
            "2. **Verzweigte Ausführung:** Je nach Ergebnis wählt das Skript den auszuführenden Codeblock.",
            "3. **Wert zurückgeben (optional):** In manchen Fällen liefern Bedingungen einen Wert, den andere Teile des Skripts nutzen können.",
        ),
        "es": _join(
            "Los condicionales son un elemento fundamental de la programación: permiten que los scripts tomen decisiones y controlen su flujo según criterios concretos. En Scheme, basado en el lenguaje de programación Scheme, los condicionales le ayudan a crear scripts dinámicos e inteligentes que se adaptan a entradas, entornos o acciones del usuario que cambian.",
            "", "### El papel de los condicionales en Scheme", "",
            "Los condicionales cumplen varias funciones clave en sus scripts:",
            "- **Dirigir la lógica:** Ejecutan distintos fragmentos de código según si ciertas condiciones son verdaderas o falsas.",
            "- **Mayor flexibilidad:** Al responder dinámicamente a entradas o estados, ayudan a manejar una variedad de escenarios.",
            "- **Simplificar la complejidad:** Descomponen la toma de decisiones en estructuras manejables, facilitando la lectura, depuración y mantenimiento del código.",
            "", "### Tipos de condicionales disponibles", "",
            "Scheme ofrece varios constructos condicionales, cada uno adaptado a distintas necesidades lógicas:",
            "- **`if`:** Para decisiones binarias simples: un bloque si la condición es verdadera y otro si es falsa.",
            "- **`cond`:** Un potente constructo de ramificación múltiple para manejar varias condiciones de forma clara y estructurada.",
            "- **`and` / `or`:** Operadores lógicos que evalúan combinaciones de condiciones y permiten decisiones más complejas.",
            "- **`else`:** Un caso comodín que define el comportamiento de respaldo cuando ninguna condición especificada se cumple.",
            "", "### Cómo funcionan los condicionales", "",
            "Los condicionales suelen implicar:",
            "1. **Evaluar una condición:** Una expresión de prueba determina si una condición es verdadera o falsa.",
            "2. **Ejecución ramificada:** Según la evaluación, el script elige qué bloque de código ejecutar.",
            "3. **Devolver un valor (opcional):** En algunos casos, los condicionales también producen un valor que otras partes del script pueden usar.",
        ),
        "fr": _join(
            "Les conditions sont un élément fondamental de la programmation : elles permettent aux scripts de prendre des décisions et de contrôler leur flux en fonction de critères précis. En Scheme, basé sur le langage de programmation Scheme, les conditions vous aident à créer des scripts dynamiques et intelligents qui s'adaptent aux entrées, environnements ou actions utilisateur changeants.",
            "", "### Le rôle des conditions en Scheme", "",
            "Les conditions remplissent plusieurs fonctions essentielles dans vos scripts :",
            "- **Diriger la logique :** Elles exécutent des morceaux de code différents selon que certaines conditions sont vraies ou fausses.",
            "- **Plus de flexibilité :** En réagissant dynamiquement aux entrées ou aux états, elles aident votre script à gérer une variété de scénarios.",
            "- **Simplifier la complexité :** Elles décomposent la prise de décision en structures gérables, rendant le code plus facile à lire, déboguer et maintenir.",
            "", "### Types de conditions disponibles", "",
            "Scheme propose plusieurs constructions conditionnelles, chacune adaptée à des besoins logiques différents :",
            "- **`if` :** Pour des décisions binaires simples — un bloc si la condition est vraie, un autre si elle est fausse.",
            "- **`cond` :** Une construction puissante à branchements multiples pour gérer plusieurs conditions de façon claire et structurée.",
            "- **`and` / `or` :** Opérateurs logiques qui évaluent des combinaisons de conditions pour une prise de décision plus complexe.",
            "- **`else` :** Un cas de repli qui définit le comportement lorsqu'aucune condition spécifiée n'est remplie.",
            "", "### Comment fonctionnent les conditions", "",
            "Les conditions impliquent généralement :",
            "1. **Évaluer une condition :** Une expression de test détermine si une condition est vraie ou fausse.",
            "2. **Exécution par branchement :** Selon l'évaluation, le script choisit le bloc de code à exécuter.",
            "3. **Retourner une valeur (facultatif) :** Dans certains cas, les conditions produisent aussi une valeur utilisable ailleurs dans le script.",
        ),
        "it": _join(
            "I condizionali sono un elemento fondamentale della programmazione: consentono agli script di prendere decisioni e controllare il flusso in base a criteri specifici. In Scheme, basato sul linguaggio di programmazione Scheme, i condizionali aiutano a creare script dinamici e intelligenti che si adattano a input, ambienti o azioni dell'utente in evoluzione.",
            "", "### Il ruolo dei condizionali in Scheme", "",
            "I condizionali svolgono diverse funzioni chiave negli script:",
            "- **Guidare la logica:** Eseguono porzioni di codice diverse a seconda che determinate condizioni siano vere o false.",
            "- **Maggiore flessibilità:** Rispondendo dinamicamente a input o stati, aiutano lo script a gestire una varietà di scenari.",
            "- **Semplificare la complessità:** Scompongono le decisioni in strutture gestibili, rendendo il codice più facile da leggere, debuggare e mantenere.",
            "", "### Tipi di condizionali disponibili", "",
            "Scheme offre diversi costrutti condizionali, ciascuno adatto a esigenze logiche differenti:",
            "- **`if`:** Per decisioni binarie semplici — un blocco se la condizione è vera, un altro se è falsa.",
            "- **`cond`:** Un potente costrutto a ramificazioni multiple per gestire più condizioni in modo chiaro e strutturato.",
            "- **`and` / `or`:** Operatori logici che valutano combinazioni di condizioni per decisioni più complesse.",
            "- **`else`:** Un caso di fallback che definisce il comportamento quando nessuna condizione specificata è soddisfatta.",
            "", "### Come funzionano i condizionali", "",
            "I condizionali implicano in genere:",
            "1. **Valutare una condizione:** Un'espressione di test determina se una condizione è vera o falsa.",
            "2. **Esecuzione ramificata:** In base alla valutazione, lo script sceglie quale blocco di codice eseguire.",
            "3. **Restituire un valore (opzionale):** In alcuni casi, i condizionali producono anche un valore utilizzabile altrove nello script.",
        ),
        "ja": _join(
            "条件分岐はプログラミングの基本要素です。スクリプトが判断を下し、特定の基準に基づいて処理の流れを制御できるようにします。Scheme 言語に基づく Scheme では、条件分岐により、入力、環境、ユーザー操作の変化に適応する動的で知的なスクリプトを作成できます。",
            "", "### Scheme における条件分岐の役割", "",
            "条件分岐はスクリプト内で次のような重要な役割を果たします。",
            "- **ロジックの制御:** 条件の真偽に応じて、異なるコード片を実行します。",
            "- **柔軟性の向上:** 入力や状態に動的に応答し、さまざまなシナリオに対応します。",
            "- **複雑さの整理:** 意思決定を管理しやすい構造に分解し、コードの読みやすさ、デバッグ、保守性を高めます。",
            "", "### 利用可能な条件構文", "",
            "Scheme には、それぞれ異なる論理ニーズに適した条件構文がいくつかあります。",
            "- **`if`:** 単純な二択 — 条件が真なら一方のブロック、偽ならもう一方を実行します。",
            "- **`cond`:** 複数条件を明確かつ構造的に扱う、強力な多分枝構文です。",
            "- **`and` / `or`:** 条件の組み合わせを評価し、より複雑な判断を可能にする論理演算子です。",
            "- **`else`:** 指定した条件のいずれも満たされない場合のフォールバック動作を定義します。",
            "", "### 条件分岐の仕組み", "",
            "条件分岐は通常、次の要素で構成されます。",
            "1. **条件の評価:** テスト式が条件の真偽を判定します。",
            "2. **分岐実行:** 評価結果に基づき、実行するコードブロックを選択します。",
            "3. **値の返却（任意）:** 場合によっては、スクリプトの他の部分で使える値を返します。",
        ),
        "ko": _join(
            "조건문은 프로그래밍의 기본 요소입니다. 스크립트가 결정을 내리고 특정 기준에 따라 흐름을 제어할 수 있게 합니다. Scheme 프로그래밍 언어에 기반한 Scheme에서는 조건문을 통해 변화하는 입력, 환경, 사용자 동작에 적응하는 동적이고 지능적인 스크립트를 작성할 수 있습니다.",
            "", "### Scheme에서 조건문의 역할", "",
            "조건문은 스크립트에서 여러 핵심 목적을 수행합니다.",
            "- **로직 제어:** 특정 조건의 참·거짓에 따라 서로 다른 코드 블록을 실행합니다.",
            "- **유연성 향상:** 입력이나 상태에 동적으로 반응하여 다양한 시나리오를 처리합니다.",
            "- **복잡성 단순화:** 의사 결정을 관리 가능한 구조로 나누어 코드를 읽고, 디버그하고, 유지하기 쉽게 만듭니다.",
            "", "### 사용 가능한 조건 구문", "",
            "Scheme은 각각 다른 논리적 요구에 맞는 여러 조건 구문을 제공합니다.",
            "- **`if`:** 단순한 이항 결정 — 조건이 참이면 한 블록, 거짓이면 다른 블록을 실행합니다.",
            "- **`cond`:** 여러 조건을 명확하고 구조적으로 처리하는 강력한 다중 분기 구문입니다.",
            "- **`and` / `or`:** 조건 조합을 평가하여 더 복잡한 결정을 가능하게 하는 논리 연산자입니다.",
            "- **`else`:** 지정된 조건이 모두 거짓일 때의 대체 동작을 정의합니다.",
            "", "### 조건문의 동작 방식", "",
            "조건문은 일반적으로 다음을 포함합니다.",
            "1. **조건 평가:** 테스트 식이 조건의 참·거짓을 판별합니다.",
            "2. **분기 실행:** 평가 결과에 따라 실행할 코드 블록을 선택합니다.",
            "3. **값 반환(선택):** 경우에 따라 스크립트의 다른 부분에서 사용할 값을 반환합니다.",
        ),
        "nl": _join(
            "Conditionals vormen een fundament onder programmeren: ze laten scripts beslissingen nemen en hun verloop sturen op basis van specifieke criteria. In Scheme, gebaseerd op de Scheme-programmeertaal, helpen conditionals u dynamische, intelligente scripts te schrijven die zich aanpassen aan veranderende invoer, omgevingen of gebruikersacties.",
            "", "### De rol van conditionals in Scheme", "",
            "Conditionals vervullen in uw scripts verschillende kernfuncties:",
            "- **Logica sturen:** Ze voeren verschillende codestukken uit, afhankelijk van of bepaalde voorwaarden waar of onwaar zijn.",
            "- **Meer flexibiliteit:** Door dynamisch te reageren op invoer of toestand helpen ze uw script een breed scala aan scenario's aan.",
            "- **Complexiteit vereenvoudigen:** Ze splitsen besluitvorming op in behapbare structuren, waardoor code makkelijker te lezen, debuggen en onderhouden is.",
            "", "### Beschikbare conditionele constructies", "",
            "Scheme biedt verschillende conditionele constructies, elk geschikt voor andere logische behoeften:",
            "- **`if`:** Voor eenvoudige binaire beslissingen — het ene codeblok als een voorwaarde waar is, het andere als die onwaar is.",
            "- **`cond`:** Een krachtige constructie met meerdere vertakkingen voor meerdere voorwaarden op een duidelijke, gestructureerde manier.",
            "- **`and` / `or`:** Logische operatoren die combinaties van voorwaarden evalueren voor complexere besluitvorming.",
            "- **`else`:** Een fallback die het gedrag definieert wanneer geen van de opgegeven voorwaarden geldt.",
            "", "### Hoe conditionals werken", "",
            "Conditionals omvatten doorgaans:",
            "1. **Een voorwaarde evalueren:** Een testexpressie bepaalt of een voorwaarde waar of onwaar is.",
            "2. **Vertakte uitvoering:** Op basis van de evaluatie kiest het script welk codeblok wordt uitgevoerd.",
            "3. **Een waarde teruggeven (optioneel):** In sommige gevallen leveren conditionals ook een waarde op die elders in het script gebruikt kan worden.",
        ),
        "pl": _join(
            "Instrukcje warunkowe to podstawa programowania: pozwalają skryptom podejmować decyzje i sterować przebiegiem wykonania według określonych kryteriów. W Scheme, opartym na języku Scheme, instrukcje warunkowe pomagają tworzyć dynamiczne, inteligentne skrypty, które dostosowują się do zmieniających się danych wejściowych, środowiska lub działań użytkownika.",
            "", "### Rola instrukcji warunkowych w Scheme", "",
            "Instrukcje warunkowe pełnią w skryptach kilka kluczowych funkcji:",
            "- **Kierowanie logiką:** Uruchamiają różne fragmenty kodu w zależności od tego, czy określone warunki są prawdziwe, czy fałszywe.",
            "- **Większa elastyczność:** Dynamicznie reagując na dane wejściowe lub stan, pomagają obsłużyć wiele scenariuszy.",
            "- **Uproszczenie złożoności:** Dzielą podejmowanie decyzji na przejrzyste struktury, ułatwiając czytanie, debugowanie i utrzymanie kodu.",
            "", "### Dostępne konstrukcje warunkowe", "",
            "Scheme oferuje kilka konstrukcji warunkowych, każda dopasowana do innych potrzeb logicznych:",
            "- **`if`:** Do prostych decyzji binarnych — jeden blok, gdy warunek jest prawdziwy, inny, gdy fałszywy.",
            "- **`cond`:** Potężna konstrukcja wielościeżkowa do obsługi wielu warunków w przejrzysty, uporządkowany sposób.",
            "- **`and` / `or`:** Operatory logiczne oceniające kombinacje warunków dla bardziej złożonych decyzji.",
            "- **`else`:** Przypadek domyślny definiujący zachowanie, gdy żaden ze wskazanych warunków nie jest spełniony.",
            "", "### Jak działają instrukcje warunkowe", "",
            "Instrukcje warunkowe zazwyczaj obejmują:",
            "1. **Ocena warunku:** Wyrażenie testowe określa, czy warunek jest prawdziwy, czy fałszywy.",
            "2. **Rozgałęziona realizacja:** Na podstawie oceny skrypt wybiera blok kodu do wykonania.",
            "3. **Zwrócenie wartości (opcjonalnie):** W niektórych przypadkach instrukcje warunkowe zwracają też wartość użyteczną w innych częściach skryptu.",
        ),
        "pt-br": _join(
            "Condicionais são um elemento fundamental da programação: permitem que scripts tomem decisões e controlem seu fluxo com base em critérios específicos. Em Scheme, baseado na linguagem de programação Scheme, os condicionais ajudam a criar scripts dinâmicos e inteligentes que se adaptam a entradas, ambientes ou ações do usuário em mudança.",
            "", "### O papel dos condicionais em Scheme", "",
            "Os condicionais cumprem várias funções essenciais nos seus scripts:",
            "- **Direcionar a lógica:** Executam trechos de código diferentes conforme certas condições são verdadeiras ou falsas.",
            "- **Mais flexibilidade:** Ao responder dinamicamente a entradas ou estados, ajudam o script a lidar com diversos cenários.",
            "- **Simplificar a complexidade:** Decompõem a tomada de decisão em estruturas gerenciáveis, facilitando leitura, depuração e manutenção do código.",
            "", "### Tipos de condicionais disponíveis", "",
            "Scheme oferece várias construções condicionais, cada uma adequada a necessidades lógicas diferentes:",
            "- **`if`:** Para decisões binárias simples — um bloco se a condição for verdadeira, outro se for falsa.",
            "- **`cond`:** Uma construção poderosa de ramificação múltipla para tratar várias condições de forma clara e estruturada.",
            "- **`and` / `or`:** Operadores lógicos que avaliam combinações de condições para decisões mais complexas.",
            "- **`else`:** Um caso padrão que define o comportamento quando nenhuma condição especificada é atendida.",
            "", "### Como funcionam os condicionais", "",
            "Condicionais normalmente envolvem:",
            "1. **Avaliar uma condição:** Uma expressão de teste determina se uma condição é verdadeira ou falsa.",
            "2. **Execução ramificada:** Com base na avaliação, o script escolhe qual bloco de código executar.",
            "3. **Retornar um valor (opcional):** Em alguns casos, os condicionais também produzem um valor utilizável em outras partes do script.",
        ),
        "ru": _join(
            "Условные конструкции — фундамент программирования: они позволяют сценариям принимать решения и управлять потоком выполнения по заданным критериям. В Scheme, основанном на языке Scheme, условия помогают создавать динамичные, гибкие сценарии, адаптирующиеся к изменяющимся входным данным, среде или действиям пользователя.",
            "", "### Роль условных конструкций в Scheme", "",
            "Условия выполняют в сценариях несколько ключевых функций:",
            "- **Управление логикой:** Запускают разные фрагменты кода в зависимости от истинности условий.",
            "- **Гибкость:** Динамически реагируя на входные данные или состояние, помогают обрабатывать множество сценариев.",
            "- **Упрощение сложности:** Разбивают принятие решений на понятные структуры, облегчая чтение, отладку и сопровождение кода.",
            "", "### Доступные условные конструкции", "",
            "Scheme предлагает несколько условных конструкций, каждая для своих логических задач:",
            "- **`if`:** Для простых бинарных решений — один блок при истинном условии, другой при ложном.",
            "- **`cond`:** Мощная многоветвевая конструкция для нескольких условий в ясной, структурированной форме.",
            "- **`and` / `or`:** Логические операторы, оценивающие комбинации условий для более сложных решений.",
            "- **`else`:** Запасной вариант, определяющий поведение, когда ни одно из указанных условий не выполнено.",
            "", "### Как работают условные конструкции", "",
            "Условия обычно включают:",
            "1. **Оценку условия:** Тестовое выражение определяет, истинно условие или ложно.",
            "2. **Ветвление:** По результату оценки сценарий выбирает блок кода для выполнения.",
            "3. **Возврат значения (необязательно):** В некоторых случаях условие также возвращает значение для других частей сценария.",
        ),
        "sv": _join(
            "Villkor är en grundläggande del av programmering: de låter skript fatta beslut och styra flödet utifrån specifika kriterier. I Scheme, baserat på programmespråket Scheme, hjälper villkor dig att skriva dynamiska, intelligenta skript som anpassar sig till förändrade indata, miljöer eller användaråtgärder.",
            "", "### Villkorens roll i Scheme", "",
            "Villkor fyller flera viktiga funktioner i dina skript:",
            "- **Styra logiken:** De kör olika kodstycken beroende på om vissa villkor är sanna eller falska.",
            "- **Ökad flexibilitet:** Genom att reagera dynamiskt på indata eller tillstånd hjälper de skriptet att hantera många scenarier.",
            "- **Förenkla komplexitet:** De delar upp beslut i hanterbara strukturer och gör koden lättare att läsa, felsöka och underhålla.",
            "", "### Tillgängliga villkorskonstruktioner", "",
            "Scheme erbjuder flera villkorskonstruktioner, var och en anpassad till olika logiska behov:",
            "- **`if`:** För enkla binära beslut — ett kodblock om villkoret är sant, ett annat om det är falskt.",
            "- **`cond`:** En kraftfull konstruktion med flera grenar för att hantera flera villkor på ett tydligt, strukturerat sätt.",
            "- **`and` / `or`:** Logiska operatorer som utvärderar kombinationer av villkor för mer komplex beslutsgivning.",
            "- **`else`:** Ett reservfall som definierar beteendet när inget av de angivna villkoren uppfylls.",
            "", "### Så fungerar villkor", "",
            "Villkor omfattar vanligtvis:",
            "1. **Utvärdera ett villkor:** Ett testuttryck avgör om ett villkor är sant eller falskt.",
            "2. **Förgrenad körning:** Utifrån utvärderingen väljer skriptet vilket kodblock som ska köras.",
            "3. **Returnera ett värde (valfritt):** I vissa fall ger villkor också ett värde som andra delar av skriptet kan använda.",
        ),
        "th": _join(
            "เงื่อนไขเป็นส่วนพื้นฐานของการเขียนโปรแกรม: ช่วยให้สคริปต์ตัดสินใจและควบคุมการไหลของงานตามเกณฑ์ที่กำหนด ใน Scheme ซึ่งอิงจากภาษา Scheme เงื่อนไขช่วยให้คุณสร้างสคริปต์ที่ยืดหยุ่นและฉลาด ปรับตัวตามข้อมูลนำเข้า สภาพแวดล้อม หรือการกระทำของผู้ใช้ที่เปลี่ยนแปลง",
            "", "### บทบาทของเงื่อนไขใน Scheme", "",
            "เงื่อนไขมีบทบาทสำคัญหลายประการในสคริปต์ของคุณ:",
            "- **กำหนดทิศทางตรรกะ:** รันโค้ดส่วนต่างๆ ตามว่าเงื่อนไขเป็นจริงหรือเท็จ",
            "- **เพิ่มความยืดหยุ่น:** ตอบสนองต่อข้อมูลนำเข้าหรือสถานะแบบไดนามิก ช่วยจัดการหลายสถานการณ์",
            "- **ลดความซับซ้อน:** แบ่งการตัดสินใจเป็นโครงสร้างที่จัดการได้ ทำให้โค้ดอ่าน ดีบัก และดูแลง่ายขึ้น",
            "", "### ประเภทของเงื่อนไขที่มี", "",
            "Scheme มีโครงสร้างเงื่อนไขหลายแบบ แต่ละแบบเหมาะกับความต้องการทางตรรกะที่ต่างกัน:",
            "- **`if`:** สำหรับการตัดสินใจแบบสองทาง — บล็อกหนึ่งเมื่อเงื่อนไขเป็นจริง อีกบล็อกเมื่อเป็นเท็จ",
            "- **`cond`:** โครงสร้างแยกสาขาหลายทางที่ทรงพลัง จัดการหลายเงื่อนไขอย่างชัดเจนและเป็นระบบ",
            "- **`and` / `or`:** ตัวดำเนินการตรรกะที่ประเมินการรวมเงื่อนไขเพื่อการตัดสินใจที่ซับซ้อนขึ้น",
            "- **`else`:** กรณีสำรองที่กำหนดพฤติกรรมเมื่อไม่มีเงื่อนไขที่ระบุเป็นจริง",
            "", "### เงื่อนไขทำงานอย่างไร", "",
            "เงื่อนไขมักเกี่ยวข้องกับ:",
            "1. **ประเมินเงื่อนไข:** นิพจน์ทดสอบกำหนดว่าเงื่อนไขเป็นจริงหรือเท็จ",
            "2. **การแยกสาขา:** ตามผลการประเมิน สคริปต์เลือกบล็อกโค้ดที่จะรัน",
            "3. **คืนค่า (ไม่บังคับ):** ในบางกรณี เงื่อนไขยังให้ค่าที่ส่วนอื่นของสคริปต์ใช้ได้",
        ),
        "zh-cn": _join(
            "条件语句是编程的基础：它们让脚本能够根据特定标准做出决策并控制执行流程。在基于 Scheme 编程语言的 Scheme 中，条件语句帮助您编写动态、智能的脚本，适应不断变化的输入、环境或用户操作。",
            "", "### 条件语句在 Scheme 中的作用", "",
            "条件语句在脚本中承担多项核心功能：",
            "- **引导逻辑：** 根据条件真假执行不同的代码段。",
            "- **提高灵活性：** 动态响应输入或状态，帮助脚本处理多种场景。",
            "- **简化复杂性：** 将决策分解为可管理的结构，使代码更易读、调试和维护。",
            "", "### 可用的条件结构", "",
            "Scheme 提供多种条件结构，各自适用于不同的逻辑需求：",
            "- **`if`：** 用于简单的二选一——条件为真执行一个代码块，为假执行另一个。",
            "- **`cond`：** 强大的多分支结构，以清晰、有序的方式处理多个条件。",
            "- **`and` / `or`：** 逻辑运算符，评估条件组合以支持更复杂的决策。",
            "- **`else`：** 兜底分支，在未满足任何指定条件时定义行为。",
            "", "### 条件语句如何工作", "",
            "条件语句通常包括：",
            "1. **评估条件：** 测试表达式判断条件为真或假。",
            "2. **分支执行：** 根据评估结果选择要执行的代码块。",
            "3. **返回值（可选）：** 某些情况下，条件语句还会产生可供脚本其他部分使用的值。",
        ),
        "zh-tw": _join(
            "條件陳述是程式設計的基礎：它們讓腳本能夠根據特定準則做出決策並控制執行流程。在基於 Scheme 程式語言的 Scheme 中，條件陳述幫助您撰寫動態、智慧的腳本，適應不斷變化的輸入、環境或使用者操作。",
            "", "### 條件陳述在 Scheme 中的角色", "",
            "條件陳述在腳本中承擔多項核心功能：",
            "- **引導邏輯：** 根據條件真假執行不同的程式碼段。",
            "- **提高彈性：** 動態回應輸入或狀態，協助腳本處理多種情境。",
            "- **簡化複雜性：** 將決策分解為可管理的結構，使程式碼更易讀、除錯和維護。",
            "", "### 可用的條件結構", "",
            "Scheme 提供多種條件結構，各自適用於不同的邏輯需求：",
            "- **`if`：** 用於簡單的二選一——條件為真執行一個程式碼區塊，為假執行另一個。",
            "- **`cond`：** 強大的多分支結構，以清晰、有序的方式處理多個條件。",
            "- **`and` / `or`：** 邏輯運算子，評估條件組合以支援更複雜的決策。",
            "- **`else`：** 兜底分支，在未滿足任何指定條件時定義行為。",
            "", "### 條件陳述如何運作", "",
            "條件陳述通常包括：",
            "1. **評估條件：** 測試運算式判斷條件為真或假。",
            "2. **分支執行：** 根據評估結果選擇要執行的程式碼區塊。",
            "3. **回傳值（可選）：** 某些情況下，條件陳述還會產生可供腳本其他部分使用的值。",
        ),
    }
    return titles[lang], bodies[lang]
